services:
  db:
    image: mysql:8.4
    container_name: horaire_eleve_db
    environment:
      MYSQL_DATABASE: horaire_eleve
      MYSQL_USER: fischer
      MYSQL_PASSWORD: adrian
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"

volumes:
  db_data:  